# Initialization

In [1]:
import pandas as pd
import numpy as np
import os
import geopandas as gpd

In [8]:
unioned_gdf = gpd.read_file(r"results\HousingSuitability.gdb", layer="UNIONED_withCenters202505")

c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts.  The processing may be really slow.  You can skip the processing by setting METHOD=SKIP.
  return ogr_read(

In [9]:
dirRoot         = r"E:\GitHub\Housing-Suitability"
dirData         = os.path.join(dirRoot,'data'        )
dirIntermediate = os.path.join(dirRoot,'intermediate')
dirResults      = os.path.join(dirRoot,'results'     )

strGDB = os.path.join(dirResults, "HousingSuitability.gdb")

strCentersIn  = os.path.join(dirData,r"Wasatch_Choice_2050_Centers_(Vision_Map)\WC2050Centers.shp")
strCentersOut = os.path.join(strGDB ,r"Centers")
strCentersOut_MC = os.path.join(strGDB ,r"MetropolitanCenters")
strCentersOut_UC = os.path.join(strGDB ,r"UrbanCenters")
strCentersOut_CC = os.path.join(strGDB ,r"CityCenters")
strCentersOut_NC = os.path.join(strGDB ,r"NeighborhoodCenters")

strSchoolsIn         = os.path.join(dirData,r"Utah_Schools__from_AGRC_-shp\Schools.dbf")
strSchoolsOut_RegPub = os.path.join(strGDB ,r"SchoolsRegPublic")
strSchoolsOut_HighEd = os.path.join(strGDB ,r"SchoolsHigherEd")

strATLinesIn  = os.path.join(dirData,r"Active_Transportation_Line_Projects_(2019-2050_RTP)\AT_lines.shp")
strATLinesOut = os.path.join(strGDB ,r"ActiveTransportationFacilities")

strTransitIn_Stops   = os.path.join(dirData,r"UTA_Stops_and_Most_Recent_Ridership\UTA_Stops_and_Most_Recent_Ridership.shp")
strTransitIn_830X    = os.path.join(dirData,r"UTA_Stops_and_Most_Recent_Ridership\UTA_Stops_and_Most_Recent_Ridership_830X.shp")
strTransitIn_BRT     = os.path.join(dirData,r"NewTransit.gdb\BRT_Stops")
strTransitIn_LRT     = os.path.join(dirData,r"NewTransit.gdb\LightRail_Stations")
strTransitIn_CRT     = os.path.join(dirData,r"NewTransit.gdb\CommuterRail_Stations")
strTransitOut_Lcl    = os.path.join(strGDB, r"LocalBusStops")
strTransitOut_BrtCur = os.path.join(strGDB, r"BRTStops")
strTransitOut_BrtFut = os.path.join(strGDB, r"BRTStops_Future")
strTransitOut_LrtCur = os.path.join(strGDB, r"LRTStops")
strTransitOut_LrtFut = os.path.join(strGDB, r"LRTStops_Future")
strTransitOut_CrtCur = os.path.join(strGDB, r"CRTStops")
strTransitOut_CrtFut = os.path.join(strGDB, r"CRTStops_Future")

strInterchangesIn_Cur  = os.path.join(dirData, r"Utah_Roads_Freeway_Exits\Roads_FreewayExits.shp")
strInterchangesIn_Fut  = os.path.join(dirData, r"Roadway_Point_Projects_(2019-2050_RTP)\Roadway_points.shp")
strInterchangesOut_Cur = os.path.join(strGDB, r"Interchanges")
strInterchangesOut_Fut = os.path.join(strGDB, r"Interchanges_Future")

strRoadsIn = os.path.join(dirData, r"UtahRoadsNetworkAnalysis_gdb\UtahRoadsNetworkAnalysis.gdb\Roads")

strATCycleTracksOut_Cur = os.path.join(strGDB, r"ATCycleTracks")
strATCycleTracksOut_Fut = os.path.join(strGDB, r"ATCycleTracks_Future")

strTrailsAndPathwaysIn = os.path.join(dirData, r"Utah_Trails_and_Pathways\TrailsAndPathways.shp")
strPathsOut_Cur        = os.path.join(strGDB, r"ATPaths")
strPathsOut_Fut        = os.path.join(strGDB, r"ATPaths_Future")

strGroceryIn           = os.path.join(dirData, r"Utah_Grocery_And_Food_Stores__UDAF_-shp\Utah_Grocery_And_Food_Stores__UDAF_.shp")
strHealthCareIn        = os.path.join(dirData, r"Utah_Health_Care_Facilities\HealthCareFacilities.shp")
strParkAccessibilityIn = os.path.join(dirData, r"Park_Accessibility__10_Minute_Walk-shp\WalkAccesstoParks_10Min_Polygons.shp")

strGroceryOut           = os.path.join(strGDB, r"GroceryStores")
strHealthCareOut        = os.path.join(strGDB, r"HealthCare")
strParkAccessibilityOut = os.path.join(strGDB, r"ParksAndOpenSpace")

strChildCareIn  = os.path.join(dirData, r"DayCare\ChildCare.shp")
strChildCareOut = os.path.join(strGDB, r"ChildCare")

strCommunityCenterIn  = os.path.join(dirData, r"Community_Centers\Community_Centers.shp")
strCommunityCenterOut = os.path.join(strGDB, r"CommunityCenter")

strQOZIn = os.path.join(dirData, r"Utah_Qualified_Opportunity_Zones-shp\UtahQualifiedOpportunityZones.shp")
strQOZOut = os.path.join(strGDB, r"UtahQualifiedOpportunityZones")

strParcelsIn  = os.path.join(dirData, r"remm_base_year_20221003\remm_base_year.gdb\parcels")
strBuildingsIn = os.path.join(dirData, r"remm_base_year_20221003\remm_base_year.gdb\buildings")
strParcelsOut = os.path.join(strGDB, "Parcels")

strMunicipalitiesIn = os.path.join(dirData, r"Utah_Municipal_Boundaries\Utah_Municipal_Boundaries.shp")
strMetroTownshipsIn = os.path.join(dirData, r"Utah_Metro_Townships\Utah_Metro_Townships.shp")
strCommunitiesOut   = os.path.join(strGDB, "Communities")

strTAZIn      = os.path.join(dirData, r"USTM_TAZ\TAZ.shp")
strAtoWfrc    = os.path.join(dirData, r"ATO_TDM_Output\ATO19_WFRC.csv")

strTAZwithATOOut = os.path.join(strGDB, "TAZWithATOScores")

def getLayerDistField(strName):
  return "dist_" + strName.rsplit('\\',1)[1]

In [10]:
dCommCode = [['Alpine'              , 'ALP'],
             ['Alta'                , 'ALA'],
             ['American Fork'       , 'AFK'],
             ['Bluffdale'           , 'BDL'],
             ['Bountiful'           , 'BTF'],
             ['Cedar Fort'          , 'CDF'],
             ['Cedar Hills'         , 'CHL'],
             ['Centerville'         , 'CEN'],
             ['Clearfield'          , 'CLR'],
             ['Clinton'             , 'CLI'],
             ['Copperton'           , 'CMT'],
             ['Cottonwood Heights'  , 'COT'],
             ['Draper'              , 'DRA'],
             ['Eagle Mountain'      , 'EAG'],
             ['Elk Ridge'           , 'ELK'],
             ['Fairfield'           , 'FFD'],
             ['Farmington'          , 'FRM'],
             ['Farr West'           , 'FRR'],
             ['Fruit Heights'       , 'FRU'],
             ['Genola'              , 'GEN'],
             ['Goshen'              , 'GOS'],
             ['Harrisville'         , 'HAR'],
             ['Herriman'            , 'HER'],
             ['Highland'            , 'HGH'],
             ['Holladay'            , 'HOL'],
             ['Hooper'              , 'HOO'],
             ['Huntsville'          , 'HVL'],
             ['Kaysville'           , 'KAY'],
             ['Kearns'              , 'KMT'],
             ['Layton'              , 'LAY'],
             ['Lehi'                , 'LEH'],
             ['Lindon'              , 'LIN'],
             ['Magna'               , 'MMT'],
             ['Mapleton'            , 'MAP'],
             ['Marriott-Slaterville', 'MSL'],
             ['Midvale'             , 'MID'],
             ['Millcreek'           , 'MLC'],
             ['Murray'              , 'MUR'],
             ['North Ogden'         , 'NOG'],
             ['North Salt Lake'     , 'NSL'],
             ['Ogden'               , 'OGD'],
             ['Orem'                , 'ORE'],
             ['Payson'              , 'PAY'],
             ['Plain City'          , 'PLN'],
             ['Pleasant Grove'      , 'PGR'],
             ['Pleasant View'       , 'PVW'],
             ['Provo'               , 'PVO'],
             ['Riverdale'           , 'RVD'],
             ['Riverton'            , 'RVT'],
             ['Roy'                 , 'ROY'],
             ['Salem'               , 'SLM'],
             ['Salt Lake City'      , 'SLC'],
             ['Sandy'               , 'SAN'],
             ['Santaquin'           , 'SAQ'],
             ['Saratoga Springs'    , 'SAR'],
             ['South Jordan'        , 'SJC'],
             ['South Ogden'         , 'SOG'],
             ['South Salt Lake'     , 'SSL'],
             ['South Weber'         , 'SWE'],
             ['Spanish Fork'        , 'SFK'],
             ['Springville'         , 'SPV'],
             ['Sunset'              , 'SUN'],
             ['Syracuse'            , 'SYR'],
             ['Taylorsville'        , 'TAY'],
             ['Uintah'              , 'UIN'],
             ['Vineyard'            , 'VIN'],
             ['Washington Terrace'  , 'WTR'],
             ['West Bountiful'      , 'WBO'],
             ['West Haven'          , 'WHV'],
             ['West Jordan'         , 'WJC'],
             ['West Point'          , 'WPT'],
             ['West Valley City'    , 'WVC'],
             ['White City'          , 'WMT'],
             ['Woodland Hills'      , 'WDL'],
             ['Woods Cross'         , 'WCR']]

dfCommCode = pd.DataFrame(dCommCode, columns=['NAME', 'CommCode'])
dfCommCode

                NAME CommCode
0             Alpine      ALP
1               Alta      ALA
2      American Fork      AFK
3          Bluffdale      BDL
4          Bountiful      BTF
..               ...      ...
70        West Point      WPT
71  West Valley City      WVC
72        White City      WMT
73    Woodland Hills      WDL
74       Woods Cross      WCR

[75 rows x 2 columns]

In [11]:
unioned_gdf.shape[0]

1725371

In [12]:
unioned_gdf.columns

Index(['FID_UNIONED', 'FID_Parcels', 'parcel_id', 'building_type',
       'SHAPE_Leng', 'FID_TAZWithATOScores', 'CO_TAZID', 'ATO_Auto_Score',
       'ATO_Tran_Score', 'FID_Interchanges_Buffers', 'dist_Interchanges',
       'FID_Interchanges_Future_Buffers', 'dist_Interchanges_Future',
       'FID_LocalBusStops_Buffers', 'dist_LocalBusStops',
       'FID_BRTStops_Buffers', 'dist_BRTStops', 'FID_BRTStops_Future_Buffers',
       'dist_BRTStops_Future', 'FID_LRTStops_Buffers', 'dist_LRTStops',
       'FID_LRTStops_Future_Buffers', 'dist_LRTStops_Future',
       'FID_CRTStops_Buffers', 'dist_CRTStops', 'FID_CRTStops_Future_Buffers',
       'dist_CRTStops_Future', 'FID_ChildCare_Buffers', 'dist_ChildCare',
       'FID_HealthCare_Buffers', 'dist_HealthCare',
       'FID_SchoolsRegPublic_Buffers', 'dist_SchoolsRegPublic',
       'FID_SchoolsHigherEd_Buffers', 'dist_SchoolsHigherEd',
       'FID_GroceryStores_Buffers', 'dist_GroceryStores',
       'FID_CommunityCenter_Buffers', 'dist_CommunityCenter',
       'FID_ATPaths_Buffers', 'dist_ATPaths', 'FID_ATPaths_Future_Buffers',
       'dist_ATPaths_Future', 'FID_ATCycleTracks_Buffers',
       'dist_ATCycleTracks', 'FID_ATCycleTracks_Future_Buffers',
       'dist_ATCycleTracks_Future', 'FID_UtahQualifiedOpportunityZones', 'QOZ',
       'SHAPE_Leng_1', 'FID_ParksAndOpenSpace', 'FID', 'FID_1', 'FacilityID',
       'SHAPE_Leng_12', 'FID_Communities', 'CommCode', 'NAME', 'COUNTYNBR',
       'Shape__Are', 'Shape__Len',
       'FID_WC2050Centers_202505_version_MetUrbCitNei_dissolve', 'CenterType',
       'Shape_Length', 'Shape_Area', 'geometry'],
      dtype='object')

In [13]:
#manually fix higher ed
unioned_gdf.loc[unioned_gdf['FID_SchoolsHigherEd_Buffers']==0.5, 'FID_SchoolsHigherEd_Buffers'] = 1.0

In [14]:
unioned_filtered_gdf = unioned_gdf[(unioned_gdf['FID_Parcels']!=-1) & (unioned_gdf['FID_Communities']!=-1)]
unioned_filtered_gdf.shape[0]

1548476

In [15]:
#sdfUnionedFiltered.spatial.to_featureclass(os.path.join(strGDB,"UNIONED_FILTERED"),sanitize_columns=False)

In [16]:
pd.set_option('display.max_rows', None)
display(unioned_filtered_gdf.groupby(['CommCode']).agg(COUNT=('FID_UNIONED','size')))
pd.set_option('display.max_rows', 10)

           COUNT
CommCode
               4
AFK        43683
ALP        15826
BDL         7236
BTF        22154
CDF         3493
CEN         8253
CHL         9869
CLI        11649
CLR        12054
CMT          373
COT        17555
DRA        25305
EAG        53347
ELK         6331
FFD         3612
FRM        12887
FRR         4242
FRU         3312
GEN         4092
GOS         1433
HAR         3686
HER        18535
HGH        24448
HOL        17141
HOO         5546
KAY        16865
KMT        14458
LAY        36632
LEH        84835
LIN        17886
MAP        18920
MID        13451
MLC        29413
MMT        12697
MSL         3294
MUR        25329
NOG        10856
NSL         8037
OGD        45079
ORE       100746
PAY        25066
PGR        37018
PLN         5471
PVO        92778
PVW         4881
ROY        18234
RVD         4896
RVT        19940
SAN        46590
SAQ        17927
SAR        45144
SFK        45227
SJC        30160
SLC       101456
SLM        15515
SOG         9221
SPV        39564
SSL        14149
SUN         3224
SWE         4537
SYR        14660
TAY        23786
UIN         1117
VIN        13095
WBO         4081
WCR         5864
WDL         3144
WHV         8086
WJC        49886
WMT         2909
WPT         6110
WTR         4432
WVC        55744

In [17]:
#myFCls = "UNIONED_WEBER_FILTERED"
#arcpy.AddField_management(os.path.join(strGDB,"UNIONED_FILTERED"), "UNIQ_ID", "LONG")
#dataDict = {}
#i = 1
#updateRows = arcpy.da.UpdateCursor(os.path.join(strGDB,"UNIONED_FILTERED"), ["OBJECTID", "UNIQ_ID"])
#for updateRow in updateRows:
#    if updateRow[0] not in dataDict:
#        dataDict[updateRow[0]] = i
#        i+=1
#    updateRow[1] = dataDict[updateRow[0]]
#    updateRows.updateRow(updateRow)
#del updateRow, updateRows

# create index
unioned_filtered_gdf = unioned_filtered_gdf.reset_index()
unioned_filtered_gdf = unioned_filtered_gdf.drop(columns=('index'))
unioned_filtered_gdf = unioned_filtered_gdf.reset_index()
unioned_filtered_gdf = unioned_filtered_gdf.rename(columns={'index':'UNIQ_ID'})
unioned_filtered_gdf

,UNIQ_ID,FID_UNIONED,FID_Parcels,parcel_id,building_type,SHAPE_Leng,FID_TAZWithATOScores,CO_TAZID,ATO_Auto_Score,ATO_Tran_Score,...,CommCode,NAME,COUNTYNBR,Shape__Are,Shape__Len,FID_WC2050Centers_202505_version_MetUrbCitNei_dissolve,CenterType,Shape_Length,Shape_Area,geometry
0,0,3635,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,FFD,Fairfield,25,1.162525e+08,55611.827949,-1,,191.013755,54.251661,"MULTIPOLYGON (((414455.324 4455643.033, 414455..."
1,1,3636,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,EAG,Eagle Mountain,25,2.260961e+08,102642.274236,-1,,197.785530,376.161994,"MULTIPOLYGON (((414455.35 4455646.75, 414455.3..."
2,2,3655,537771,542397.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,FFD,Fairfield,25,1.162525e+08,55611.827949,-1,,951.466787,46411.108390,"MULTIPOLYGON (((410414.971 4456909.281, 410414..."
3,3,3674,540680,545427.0,Empty Buildable,0.000000,-1,0,0.000000,0.000000,...,FFD,Fairfield,25,1.162525e+08,55611.827949,-1,,202.045503,49.516802,"MULTIPOLYGON (((411519.359 4452426.926, 411519..."
4,4,3712,566001,571134.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,FFD,Fairfield,25,1.162525e+08,55611.827949,-1,,2182.413872,233893.646255,"MULTIPOLYGON (((410635.742 4457314.507, 410635..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548471,1548471,1728592,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,LAY,Layton,06,1.031110e+08,88068.259149,324,Urban Center,29.854844,0.025347,"MULTIPOLYGON (((418755.129 4545928.895, 418763..."
1548472,1548472,1728593,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,LAY,Layton,06,1.031110e+08,88068.259149,324,Urban Center,29.854844,0.025347,"MULTIPOLYGON (((418755.129 4545928.895, 418763..."
1548473,1548473,1728597,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,LAY,Layton,06,1.031110e+08,88068.259149,324,Urban Center,21.658295,0.124203,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."
1548474,1548474,1728598,1947,2047.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,LAY,Layton,06,1.031110e+08,88068.259149,324,Urban Center,21.658295,0.124203,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."
1548475,1548475,1728599,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,LAY,Layton,06,1.031110e+08,88068.259149,324,Urban Center,21.658295,0.124203,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."

# DataFrame processing

In [18]:
# Centers Scores

strCenterColName = 'CenterType'

dfCenters = pd.DataFrame({'center_code':['CM'                 ,'CU'          ,'CC'         ,'CN'                 ],
                          'center_name':['Metropolitan Center','Urban Center','City Center','Neighborhood Center']})
display(dfCenters)

for index, row in dfCenters.iterrows():
    _cname = row['center_name']
    _ccode = row['center_code']
    print(_cname)
    
    unioned_filtered_gdf[_ccode] = 0
    
    unioned_filtered_gdf.loc[(unioned_filtered_gdf[strCenterColName]==_cname),_ccode] = 1
    
# sum for check
display(unioned_filtered_gdf[['CM','CU','CC','CN']].sum())
display(unioned_filtered_gdf[['CM','CU','CC','CN']].max())

  center_code          center_name
0          CM  Metropolitan Center
1          CU         Urban Center
2          CC          City Center
3          CN  Neighborhood Center

Metropolitan Center
Urban Center
City Center
Neighborhood Center

CM    10514
CU    41534
CC    48916
CN    19532
dtype: int64

CM    1
CU    1
CC    1
CN    1
dtype: int64

In [19]:
# ATO Scores
unioned_filtered_gdf['AA'] = unioned_filtered_gdf['ATO_Auto_Score']
unioned_filtered_gdf['AT'] = unioned_filtered_gdf['ATO_Tran_Score']

# sum for check
display(unioned_filtered_gdf[['AA','AT']].sum())
display(unioned_filtered_gdf[['AA','AT']].max())

AA    1.221966e+06
AT    4.708288e+05
dtype: float64

AA    1.0
AT    1.0
dtype: float64

In [20]:
# Transportation Scores

unioned_filtered_gdf['TT'] = 0
# Transit only has single buffers
# local bus get 1/2 score, all other gets full score
unioned_filtered_gdf.loc[ (unioned_filtered_gdf['FID_LocalBusStops_Buffers'  ]!=-1) ,'TT'] = 0.5
# local bus values are overwritten by other modes
unioned_filtered_gdf.loc[((unioned_filtered_gdf['FID_BRTStops_Buffers'       ]!=-1) |
                        (unioned_filtered_gdf['FID_BRTStops_Future_Buffers']!=-1) |
                        (unioned_filtered_gdf['FID_LRTStops_Buffers'       ]!=-1) |
                        (unioned_filtered_gdf['FID_LRTStops_Future_Buffers']!=-1) |
                        (unioned_filtered_gdf['FID_CRTStops_Buffers'       ]!=-1) |
                        (unioned_filtered_gdf['FID_CRTStops_Future_Buffers']!=-1)),'TT'] = 1


# Freeway Access
dfFreewayAccess = pd.DataFrame({'tempscore' :['TF1'                                    ,'TF2'                                    ],
                                'moe'       :['Interchanges_Buffers'                   ,'Interchanges_Future_Buffers'            ],
                                'fieldname' :[getLayerDistField(strInterchangesOut_Cur),getLayerDistField(strInterchangesOut_Fut)],
                                'smallest'  :[0.5                                      ,0.5                                      ]})
                                # smallest buffer
display(dfFreewayAccess)

# future

for index, row in dfFreewayAccess.iterrows():
    unioned_filtered_gdf[row['tempscore']] = 1 / (unioned_filtered_gdf[row['fieldname']] * (1 / row['smallest'])) # equation insures smallest buffer score is always 1
    unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
    
unioned_filtered_gdf['TF'] = unioned_filtered_gdf[dfFreewayAccess['tempscore'].tolist()].values.max(1)

# Active Transportation Access 
dfATAccess = pd.DataFrame({'tempscore' :['TA1'                             ,'TA2'                             ,'TA3'                                     ,'TA4'                                     ],
                           'moe'       :['ATPaths_Buffers'                 ,'ATPaths_Future_Buffers'          ,'ATCycleTracks_Buffers'                   ,'ATCycleTracks_Future_Buffers'            ],
                           'fieldname' :[getLayerDistField(strPathsOut_Cur),getLayerDistField(strPathsOut_Fut),getLayerDistField(strATCycleTracksOut_Cur),getLayerDistField(strATCycleTracksOut_Fut)],
                           'smallest'  :[0.5                               ,0.5                               ,0.5                                       ,0.5                                       ]})
                            #multiplier is equal to 1 / the largest buffer distance                  
display(dfATAccess)

for index, row in dfATAccess.iterrows():
    unioned_filtered_gdf[row['tempscore']] = 1 / (unioned_filtered_gdf[row['fieldname']] * (1 / row['smallest'])) # equation insures smallest buffer score is always 1
    unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)

unioned_filtered_gdf['TA'] = unioned_filtered_gdf[dfATAccess['tempscore'].tolist()].values.max(1)

# sum for check
display(unioned_filtered_gdf[['TT','TF1','TF2','TF','TA']].sum())
display(unioned_filtered_gdf[['TT','TF1','TF2','TF','TA']].max())

C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  unioned_filtered_gdf.loc[ (unioned_filtered_gdf['FID_LocalBusStops_Buffers'  ]!=-1) ,'TT'] = 0.5

  tempscore                          moe                 fieldname  smallest
0       TF1         Interchanges_Buffers         dist_Interchanges       0.5
1       TF2  Interchanges_Future_Buffers  dist_Interchanges_Future       0.5

C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)

  tempscore                           moe                  fieldname  smallest
0       TA1               ATPaths_Buffers               dist_ATPaths       0.5
1       TA2        ATPaths_Future_Buffers        dist_ATPaths_Future       0.5
2       TA3         ATCycleTracks_Buffers         dist_ATCycleTracks       0.5
3       TA4  ATCycleTracks_Future_Buffers  dist_ATCycleTracks_Future       0.5

C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\3874546525.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)

TT      388450.00
TF1     274729.75
TF2      75077.75
TF      324216.75
TA     1371932.25
dtype: float64

TT     1.0
TF1    1.0
TF2    1.0
TF     1.0
TA     1.0
dtype: float64

In [21]:
unioned_filtered_gdf

,UNIQ_ID,FID_UNIONED,FID_Parcels,parcel_id,building_type,SHAPE_Leng,FID_TAZWithATOScores,CO_TAZID,ATO_Auto_Score,ATO_Tran_Score,...,AT,TT,TF1,TF2,TF,TA1,TA2,TA3,TA4,TA
0,0,3635,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
1,1,3636,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
2,2,3655,537771,542397.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
3,3,3674,540680,545427.0,Empty Buildable,0.000000,-1,0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
4,4,3712,566001,571134.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548471,1548471,1728592,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,0.953679,1.0,0.5,0.0,0.5,1.0,1.0,0.0,0.25,1.0
1548472,1548472,1728593,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,0.953679,1.0,0.5,0.0,0.5,1.0,1.0,0.0,0.25,1.0
1548473,1548473,1728597,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,0.953679,1.0,0.5,0.0,0.5,1.0,1.0,0.0,0.25,1.0
1548474,1548474,1728598,1947,2047.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,0.953679,1.0,0.5,0.0,0.5,1.0,1.0,0.0,0.25,1.0
1548475,1548475,1728599,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,0.953679,1.0,0.5,0.0,0.5,1.0,1.0,0.0,0.25,1.0

# Amenities Scores

In [22]:
#score multipliers - match to buffers above - so that max is always 1.0
#                                         Child Care                         Healthcare                          Grocery                          Community Center
dfAmenities = pd.DataFrame({'scorename' :['AC'                              ,'AH'                               ,'AG'                            ,'AM'                                    ],
                            'distfield' :[getLayerDistField(strChildCareOut),getLayerDistField(strHealthCareOut),getLayerDistField(strGroceryOut),getLayerDistField(strCommunityCenterOut)],
                            'smallest'  :[0.5                               ,0.5                                ,0.5                             ,0.5                                     ]})

display(dfAmenities)

for index, row in dfAmenities.iterrows():
    unioned_filtered_gdf[row['scorename']] = 1 / (unioned_filtered_gdf[row['distfield']] * (1 / row['smallest']))
    unioned_filtered_gdf[row['scorename']].replace([np.inf, -np.inf], 0, inplace=True)

# Education Access
dfEducation = pd.DataFrame({'tempscore' :['AE1'                                  ,'AE2'                                  ],
                            'moe'       :['SchoolsRegPublic_Buffers'             ,'SchoolsHigherEd_Buffers '             ],
                            'fieldname' :[getLayerDistField(strSchoolsOut_RegPub),getLayerDistField(strSchoolsOut_HighEd)],
                            'smallest'  :[0.5                                    ,1                                      ]})
                            # smallest buffer size

display(dfEducation)

for index, row in dfEducation.iterrows():
    unioned_filtered_gdf[row['tempscore']] = 1 / (unioned_filtered_gdf[row['fieldname']] * (1 / row['smallest'])) # equation insures smallest buffer score is always 1
    unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)

unioned_filtered_gdf['AE'] = unioned_filtered_gdf[dfEducation['tempscore'].tolist()].values.max(1)


# Parks and Open Space

unioned_filtered_gdf['AP'] = 0
    
unioned_filtered_gdf.loc[(unioned_filtered_gdf['FID_ParksAndOpenSpace']==1),'AP'] = 1


# sum for check
display(unioned_filtered_gdf[['AC','AH','AE1','AE2','AE','AG','AP','AM']].sum())
display(unioned_filtered_gdf[['AC','AH','AE1','AE2','AE','AG','AP','AM']].max())

  scorename             distfield  smallest
0        AC        dist_ChildCare       0.5
1        AH       dist_HealthCare       0.5
2        AG    dist_GroceryStores       0.5
3        AM  dist_CommunityCenter       0.5

C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['scorename']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['scorename']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['scorename']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['scorename']].replace([np.inf, -np.inf], 0, inplace=True)

  tempscore                       moe              fieldname  smallest
0       AE1  SchoolsRegPublic_Buffers  dist_SchoolsRegPublic       0.5
1       AE2  SchoolsHigherEd_Buffers    dist_SchoolsHigherEd       1.0

C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)
C:\Users\bhereth\AppData\Local\Temp\ipykernel_10652\6224146.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_filtered_gdf[row['tempscore']].replace([np.inf, -np.inf], 0, inplace=True)

AC      663270.5
AH      416422.0
AE1     952475.5
AE2     241006.0
AE     1009122.0
AG      689567.5
AP      691295.0
AM      444573.0
dtype: float64

AC     1.0
AH     1.0
AE1    1.0
AE2    2.0
AE     2.0
AG     1.0
AP     1.0
AM     1.0
dtype: float64

# Opportunity Zone

In [23]:
# Parks and Open Space

unioned_filtered_gdf['OZ'] = 0
    
unioned_filtered_gdf.loc[(unioned_filtered_gdf['FID_UtahQualifiedOpportunityZones']!=-1),'OZ'] = 1

# Building Code

In [24]:
dBuildingCodes= [
    ["AG","Agriculture"             ], 
    ["EM","Empty Buildable"         ],
    ["OS","Open Space Non-Buildable"],
    ["CH","Church"                  ],
    ["SF","Single Family Res"       ],
    ["MF","Multi Family Res"        ],
    ["GQ","Group Quarters"          ],
    ["GO","Governmental"            ],
    ["ED","Educational"             ],
    ["HE","Healthcare"              ],
    ["RE","Retail"                  ],
    ["OF","Office"                  ],
    ["IN","Industrial"              ],
    ["OT","Other"                   ],
    ["UT","Utilities"               ],
    ["NB","No Build"                ]
]

dfBuildingCodes = pd.DataFrame(dBuildingCodes, columns = ['BC','building_type'])
display(dfBuildingCodes)


unioned_filtered_with_bc_gdf = pd.DataFrame.merge(unioned_filtered_gdf,dfBuildingCodes,on='building_type',how='left')
unioned_filtered_with_bc_gdf['BC'] = unioned_filtered_with_bc_gdf['BC'].fillna('NO')
unioned_filtered_with_bc_gdf

    BC             building_type
0   AG               Agriculture
1   EM           Empty Buildable
2   OS  Open Space Non-Buildable
3   CH                    Church
4   SF         Single Family Res
..  ..                       ...
11  OF                    Office
12  IN                Industrial
13  OT                     Other
14  UT                 Utilities
15  NB                  No Build

[16 rows x 2 columns]

,UNIQ_ID,FID_UNIONED,FID_Parcels,parcel_id,building_type,SHAPE_Leng,FID_TAZWithATOScores,CO_TAZID,ATO_Auto_Score,ATO_Tran_Score,...,AC,AH,AG,AM,AE1,AE2,AE,AP,OZ,BC
0,0,3635,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NB
1,1,3636,505175,509243.0,No Build,0.000000,-1,0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NB
2,2,3655,537771,542397.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,OS
3,3,3674,540680,545427.0,Empty Buildable,0.000000,-1,0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,EM
4,4,3712,566001,571134.0,Open Space Non-Buildable,0.000000,-1,0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,OS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548471,1548471,1728592,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,1.0,0.5,1.0,1.0,1.0,0.0,1.0,1,1,RE
1548472,1548472,1728593,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,1.0,0.5,1.0,1.0,1.0,0.0,1.0,1,1,RE
1548473,1548473,1728597,1938,2038.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,1.0,0.5,1.0,1.0,1.0,0.0,1.0,1,1,RE
1548474,1548474,1728598,1947,2047.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,1.0,0.5,1.0,1.0,1.0,0.0,1.0,1,1,RE
1548475,1548475,1728599,1954,2054.0,Retail,9551.762084,1969,110513,0.857921,0.953679,...,1.0,0.5,1.0,1.0,1.0,0.0,1.0,1,1,RE

In [25]:
unioned_filtered_with_bc_gdf.columns

Index(['UNIQ_ID', 'FID_UNIONED', 'FID_Parcels', 'parcel_id', 'building_type',
       'SHAPE_Leng', 'FID_TAZWithATOScores', 'CO_TAZID', 'ATO_Auto_Score',
       'ATO_Tran_Score', 'FID_Interchanges_Buffers', 'dist_Interchanges',
       'FID_Interchanges_Future_Buffers', 'dist_Interchanges_Future',
       'FID_LocalBusStops_Buffers', 'dist_LocalBusStops',
       'FID_BRTStops_Buffers', 'dist_BRTStops', 'FID_BRTStops_Future_Buffers',
       'dist_BRTStops_Future', 'FID_LRTStops_Buffers', 'dist_LRTStops',
       'FID_LRTStops_Future_Buffers', 'dist_LRTStops_Future',
       'FID_CRTStops_Buffers', 'dist_CRTStops', 'FID_CRTStops_Future_Buffers',
       'dist_CRTStops_Future', 'FID_ChildCare_Buffers', 'dist_ChildCare',
       'FID_HealthCare_Buffers', 'dist_HealthCare',
       'FID_SchoolsRegPublic_Buffers', 'dist_SchoolsRegPublic',
       'FID_SchoolsHigherEd_Buffers', 'dist_SchoolsHigherEd',
       'FID_GroceryStores_Buffers', 'dist_GroceryStores',
       'FID_CommunityCenter_Buffers', 'dist_CommunityCenter',
       'FID_ATPaths_Buffers', 'dist_ATPaths', 'FID_ATPaths_Future_Buffers',
       'dist_ATPaths_Future', 'FID_ATCycleTracks_Buffers',
       'dist_ATCycleTracks', 'FID_ATCycleTracks_Future_Buffers',
       'dist_ATCycleTracks_Future', 'FID_UtahQualifiedOpportunityZones', 'QOZ',
       'SHAPE_Leng_1', 'FID_ParksAndOpenSpace', 'FID', 'FID_1', 'FacilityID',
       'SHAPE_Leng_12', 'FID_Communities', 'CommCode', 'NAME', 'COUNTYNBR',
       'Shape__Are', 'Shape__Len',
       'FID_WC2050Centers_202505_version_MetUrbCitNei_dissolve', 'CenterType',
       'Shape_Length', 'Shape_Area', 'geometry', 'CM', 'CU', 'CC', 'CN', 'AA',
       'AT', 'TT', 'TF1', 'TF2', 'TF', 'TA1', 'TA2', 'TA3', 'TA4', 'TA', 'AC',
       'AH', 'AG', 'AM', 'AE1', 'AE2', 'AE', 'AP', 'OZ', 'BC'],
      dtype='object')

In [27]:
unioned_filtered_scores_gdf = unioned_filtered_with_bc_gdf[['UNIQ_ID','CommCode','COUNTYNBR','BC','OZ','CM','CU','CC','CN','AA','AT','TT','TF','TA','AC','AH','AE','AG','AP','AM','geometry']]
display(unioned_filtered_scores_gdf)
display(unioned_filtered_scores_gdf.describe())
#display(unioned_filtered_scores_gdf.sum())

,UNIQ_ID,CommCode,COUNTYNBR,BC,OZ,CM,CU,CC,CN,AA,...,TT,TF,TA,AC,AH,AE,AG,AP,AM,geometry
0,0,FFD,25,NB,0,0,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,"MULTIPOLYGON (((414455.324 4455643.033, 414455..."
1,1,EAG,25,NB,0,0,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,"MULTIPOLYGON (((414455.35 4455646.75, 414455.3..."
2,2,FFD,25,OS,0,0,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,"MULTIPOLYGON (((410414.971 4456909.281, 410414..."
3,3,FFD,25,EM,0,0,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,"MULTIPOLYGON (((411519.359 4452426.926, 411519..."
4,4,FFD,25,OS,0,0,0,0,0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,"MULTIPOLYGON (((410635.742 4457314.507, 410635..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548471,1548471,LAY,06,RE,1,0,1,0,0,0.857921,...,1.0,0.5,1.0,1.0,0.5,1.0,1.0,1,1.0,"MULTIPOLYGON (((418755.129 4545928.895, 418763..."
1548472,1548472,LAY,06,RE,1,0,1,0,0,0.857921,...,1.0,0.5,1.0,1.0,0.5,1.0,1.0,1,1.0,"MULTIPOLYGON (((418755.129 4545928.895, 418763..."
1548473,1548473,LAY,06,RE,1,0,1,0,0,0.857921,...,1.0,0.5,1.0,1.0,0.5,1.0,1.0,1,1.0,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."
1548474,1548474,LAY,06,RE,1,0,1,0,0,0.857921,...,1.0,0.5,1.0,1.0,0.5,1.0,1.0,1,1.0,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."
1548475,1548475,LAY,06,RE,1,0,1,0,0,0.857921,...,1.0,0.5,1.0,1.0,0.5,1.0,1.0,1,1.0,"MULTIPOLYGON (((418748.651 4545936.587, 418759..."

,UNIQ_ID,OZ,CM,CU,CC,CN,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
count,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06,1.548476e+06
mean,7.742375e+05,5.058522e-02,6.789902e-03,2.682250e-02,3.158977e-02,1.261369e-02,7.891412e-01,3.040594e-01,2.508596e-01,2.093780e-01,8.859887e-01,4.283376e-01,2.689238e-01,6.516872e-01,4.453201e-01,4.464357e-01,2.871036e-01
std,4.470067e+05,2.191492e-01,8.212066e-02,1.615645e-01,1.749053e-01,1.116002e-01,1.548443e-01,2.828857e-01,3.546046e-01,2.606060e-01,2.299024e-01,4.044862e-01,3.603827e-01,3.987619e-01,3.968230e-01,4.971227e-01,2.886439e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.871188e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.227040e-01,1.375256e-02,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00
50%,7.742375e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.223714e-01,2.504206e-01,0.000000e+00,2.500000e-01,1.000000e+00,5.000000e-01,0.000000e+00,5.000000e-01,5.000000e-01,0.000000e+00,2.500000e-01
75%,1.161356e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.980730e-01,4.945305e-01,5.000000e-01,2.500000e-01,1.000000e+00,1.000000e+00,5.000000e-01,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e-01
max,1.548475e+06,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [40]:
unioned_filtered_scores_gdf.dtypes

UNIQ_ID         int64
CommCode       object
COUNTYNBR      object
BC             object
OZ            float64
               ...
AE            float64
AG            float64
AP            float64
AM            float64
geometry     geometry
Length: 21, dtype: object

In [39]:
unioned_filtered_scores_gdf['OZ'] = unioned_filtered_scores_gdf['OZ'].astype('float64')
unioned_filtered_scores_gdf['CM'] = unioned_filtered_scores_gdf['CM'].astype('float64')
unioned_filtered_scores_gdf['CU'] = unioned_filtered_scores_gdf['CU'].astype('float64')
unioned_filtered_scores_gdf['CC'] = unioned_filtered_scores_gdf['CC'].astype('float64')
unioned_filtered_scores_gdf['CN'] = unioned_filtered_scores_gdf['CN'].astype('float64')
unioned_filtered_scores_gdf['AP'] = unioned_filtered_scores_gdf['AP'].astype('float64')

c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
c:\Users\bhereth\AppData\Local\anaconda3\envs\july2025\Lib\site-packages\geopandas\geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [41]:
# export final feature class
#unioned_filtered_scores_gdf.spatial.to_featureclass(os.path.join(strGDB, r"ParcelPartsWithScores"),sanitize_columns=False)

unioned_filtered_scores_gdf.to_file("results/UNIONED_withCenters202505.gpkg", layer="unioned", driver="GPKG")

#

In [43]:
# DISSOLVE MANUALLY DONE IN ARCGIS PRO
# Parcel Parts With Scores
# dissolve fields: ['CommCode','COUNTYNBR','BC','OZ','CM','CU','CC','CN','AA','AT','TT','TF','TA','AC','AH','AE','AG','AP','AM']

In [31]:
dfCommCodeCat = unioned_filtered_scores_gdf.groupby(['CommCode'],as_index=False).agg(OZ=('OZ','max'),
                                                                                   CM=('CM','max'),
                                                                                   CU=('CU','max'),
                                                                                   CC=('CC','max'),
                                                                                   CN=('CN','max'),
                                                                                   AA=('AA','max'),
                                                                                   AT=('AT','max'),
                                                                                   TT=('TT','max'),
                                                                                   TF=('TF','max'),
                                                                                   TA=('TA','max'),
                                                                                   AC=('AC','max'),
                                                                                   AH=('AH','max'),
                                                                                   AE=('AE','max'),
                                                                                   AG=('AG','max'),
                                                                                   AP=('AP','max'),
                                                                                   AM=('AM','max'))

dfCommCodeCat_melt = pd.melt(dfCommCodeCat, id_vars='CommCode', value_vars=['OZ','CM','CU','CC','CN','AA','AT','TT','TF','TA','AC','AH','AE','AG','AP','AM'], var_name='Cat', value_name='CatValue', col_level=None)

dfCommCodeCatWithValues = dfCommCodeCat_melt[dfCommCodeCat_melt['CatValue']>0].copy()
dfCommCodeCatWithValues.drop(columns=['CatValue'],inplace=True)
dfCommCodeValidCategories = dfCommCodeCatWithValues[~dfCommCodeCatWithValues['Cat'].str.startswith('OZ')]
dfCommCodeValidCategories = dfCommCodeCatWithValues.groupby(['CommCode'],as_index=False).agg(['unique'])
dfCommCodeValidCategories = dfCommCodeValidCategories.droplevel(level=0, axis=1)
dfCommCodeValidCategories = dfCommCodeValidCategories.reset_index()
dfCommCodeValidCategories = dfCommCodeValidCategories.rename(columns={'unique':'categories'})
dfCommCodeValidCategories['categories'] = [','.join(map(str, l)) for l in dfCommCodeValidCategories['categories']]
dfCommCodeValidCategories

    index                                         categories
0       0                                        OZ,CC,CN,TT
1       1  AFK        OZ,CC,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
2       2  ALP                    AA,AT,TA,AC,AH,AE,AG,AP,AM
3       3  BDL        CU,CC,CN,AA,AT,TT,TF,TA,AC,AE,AG,AP,AM
4       4  BTF     CU,CC,CN,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
..    ...  ...                                           ...
69     69  WJC  OZ,CU,CC,CN,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
70     70  WMT           CN,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
71     71  WPT              CC,CN,AA,AT,TT,TA,AC,AH,AE,AG,AP
72     72  WTR           CC,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM
73     73  WVC  OZ,CU,CC,CN,AA,AT,TT,TF,TA,AC,AH,AE,AG,AP,AM

[74 rows x 3 columns]

In [32]:
dfCommCodeValidCenters = dfCommCodeCat_melt[dfCommCodeCat_melt['CatValue']>0].copy()
dfCommCodeValidCenters.drop(columns=['CatValue'],inplace=True)
dfCommCodeValidCenters = dfCommCodeValidCenters[dfCommCodeValidCenters['Cat'].str.startswith('C')]
dfCommCodeValidCenters = dfCommCodeValidCenters.groupby(['CommCode'],as_index=False).agg(['unique'])
dfCommCodeValidCenters = dfCommCodeValidCenters.droplevel(level=0, axis=1)
dfCommCodeValidCenters = dfCommCodeValidCenters.reset_index()
dfCommCodeValidCenters = dfCommCodeValidCenters.rename(columns={'unique':'centers'})
dfCommCodeValidCenters['centers'] = [','.join(map(str, l)) for l in dfCommCodeValidCenters['centers']]
dfCommCodeValidCenters

    index        centers
0       0          CC,CN
1       1  AFK        CC
2       2  BDL  CU,CC,CN
3       3  BTF  CU,CC,CN
4       4  CEN     CC,CN
..    ...  ...       ...
58     58  WJC  CU,CC,CN
59     59  WMT        CN
60     60  WPT     CC,CN
61     61  WTR        CC
62     62  WVC  CU,CC,CN

[63 rows x 3 columns]

In [34]:
dfCommCodeCatWithOZ = unioned_filtered_scores_gdf.groupby(['CommCode'],as_index=False).agg(OZ=('OZ','max'))
dfCommCodeCatWithOZ
dfCommCodeCatWithOZ.loc[dfCommCodeCatWithOZ['OZ']>0,'oppzones']='yes'
dfCommCodeCatWithOZ.loc[dfCommCodeCatWithOZ['OZ']==0,'oppzones']='no'
dfCommCodeCatWithOZ.drop(columns=['OZ'],inplace=True)
dfCommCodeCatWithOZ

   CommCode oppzones
0                yes
1       AFK      yes
2       ALP       no
3       BDL       no
4       BTF       no
..      ...      ...
69      WJC      yes
70      WMT       no
71      WPT       no
72      WTR       no
73      WVC      yes

[74 rows x 2 columns]

In [35]:
dfCommunitiesForApp = unioned_filtered_scores_gdf.copy()
dfCommunitiesForApp = dfCommunitiesForApp[['NAME','CommCode','COUNTYNBR']]
dfCommunitiesForApp = pd.DataFrame.merge(dfCommunitiesForApp,dfCommCodeCatWithOZ      ,on='CommCode',how='left')
dfCommunitiesForApp = pd.DataFrame.merge(dfCommunitiesForApp,dfCommCodeValidCenters   ,on='CommCode',how='left')
dfCommunitiesForApp = pd.DataFrame.merge(dfCommunitiesForApp,dfCommCodeValidCategories,on='CommCode',how='left')
dfCommunitiesForApp.rename(columns={'CommCode':'value','NAME':'label'},inplace=True)
dfCommunitiesForApp = dfCommunitiesForApp.sort_values(by=['label'])
dfCommunitiesForApp.to_json('communities.json',orient='records')
dfCommunitiesForApp

KeyError: "['NAME'] not in index"